### PR TITLE
DMP 2024 Issue Template 

### PR DESCRIPTION
**Pull request by NiranjanAP**
Dedicated Mentoring Program (DMP) 2024 is an initiative from C4GT team to engage Open Source Developers into project development. Dhiway is participating in this program.
https://www.codeforgovtech.in/ 
This PR sets up a template for issue creation for this program, it helps in showing it in their dashboard.

### CODE REVIEW

**Comment by amarts** [comment]
Would be great to add more details on what is DMP and all that in the description of the issue.

**Review by amarts — COMMENTED** [review]
Content looks fine. Would be great to have reference to DMP (url?) in the description for merging.

**Comment by NiranjanAP** [comment]
> Content looks fine. Would be great to have reference to DMP (url?) in the description for merging.

updated

**Comment by NiranjanAP** [comment]
> Content looks fine. Would be great to have reference to DMP (url?) in the description for merging.

updated

**Review by amarts — APPROVED** [review]

**Pull request merged**
