### PR TITLE
Remove unnecessary flags from `Makefile` build stages.

### PR DESCRIPTION
**Pull request by roynrishingha**

### CODE REVIEW

**Comment by roynrishingha** [comment]
@adi-a11y This PR will fix the errors you encountered.

**Comment by belyrs** [comment]
> @adi-a11y This PR will fix the errors you encountered.

Thank you

**Review by amarts — APPROVED** [review]

**Review by NiranjanAP — APPROVED** [review]

**Comment by NiranjanAP** [comment]
@roynrishingha  - which option was actually causing the issue?

**Comment by amarts** [comment]
> @roynrishingha - which option was actually causing the issue?

Good to decipher this, for our own understanding.

**Comment by roynrishingha** [comment]
@amarts @NiranjanAP The issue was with `--all-targets --features=runtime-benchmarks`. It was a mistake from my side. `cargo build` does not require these.

**Comment by NiranjanAP** [comment]
it was clear that those options were causing the issue hence you removed, I just wanted to understand why...

**Pull request merged**
