### PR TITLE
[C4GT] Asset: Added test for InvalidAssetType Issue #374

### LINKED ISSUE #374: [C4GT] Asset: Add tests for `InvalidAssetType`
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-asset` after adding it in the code.

## Goals

- [ ] Add tests for `InvalidAssetType` for pallet/asset

## Expected Outcome
- [ ] Test should assert for `InvalidAssetType` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: check method `asset_create_should_succeed` which validates creation of asset.

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts @vatsa287 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

### PR DESCRIPTION
**Pull request by hardik-pratap-singh**
Fixes #374 
Added tests for `InvalidAssetType` for pallet/asset
@vatsa287 @amarts

### CODE REVIEW

**Comment by hardik-pratap-singh** [comment]
Hey @vatsa287  @amarts !
All checks have passed.. 
Please review it.

**Review by vatsa287 — CHANGES_REQUESTED** [review]
@hardik-pratap-singh Even though the tests have passed, I doubt that else branch is actually being executed. 
Since initially asset type has been set to `MF`. And in if condition it is being checked if type is of any 3 valid types. So if part is executed and not else.
So the error code is not being checked.
Please add a log and check.

**Comment by hardik-pratap-singh** [comment]
> @hardik-pratap-singh Even though the tests have passed, I doubt that else branch is actually being executed. Since initially asset type has been set to `MF`. And in if condition it is being checked if type is of any 3 valid types. So if part is executed and not else. So the error code is not being checked. Please add a log and check.

@vatsa287 ! I was also thinking the same. But everywhere I can find asset_type being initialized with MF. How can I actually get the asset_type ?

**Comment by vatsa287** [comment]
> > @hardik-pratap-singh Even though the tests have passed, I doubt that else branch is actually being executed. Since initially asset type has been set to `MF`. And in if condition it is being checked if type is of any 3 valid types. So if part is executed and not else. So the error code is not being checked. Please add a log and check.
> 
> @vatsa287 ! I was also thinking the same. But everywhere I can find asset_type being initialized with MF. How can I actually get the asset_type ?

Check pallets/src/types.rs where we define `AssetTypeOf` to be ,
```
pub enum AssetTypeOf {
	ART,
	BOND,
	MF,
}
```

**Comment by hardik-pratap-singh** [comment]
> > > @hardik-pratap-singh Even though the tests have passed, I doubt that else branch is actually being executed. Since initially asset type has been set to `MF`. And in if condition it is being checked if type is of any 3 valid types. So if part is executed and not else. So the error code is not being checked. Please add a log and check.
> > 
> > 
> > @vatsa287 ! I was also thinking the same. But everywhere I can find asset_type being initialized with MF. How can I actually get the asset_type ?
> 
> Check pallets/src/types.rs where we define `AssetTypeOf` to be ,
> 
> ```
> pub enum AssetTypeOf {
> 	ART,
> 	BOND,
> 	MF,
> }
> ```

I wanted to ask that all of the values i.e. `asset_desc` , `asset_tag` , `asset_meta` , `asset_qty` , `asset_value` and `asset_type` are being hard coded right ? Or we are getting them dynamically from somewhere ? <br> If we don't have to hard code the value just like we did for `asset_type` as `MF`, what can we write for asset_type ? <br> Currently we have this : `let asset_type = AssetTypeOf::MF` <br><br> We can add a new asset type called `Invalid` and pass `AssetTypeOf::Invalid` to get the else part in function. But I don't think that will be a good practice.

**Comment by hardik-pratap-singh** [comment]
@vatsa287 Can you help me with it ?

**Comment by hardik-pratap-singh** [comment]
Hey @vatsa287 @NiranjanAP @amarts !
I am stuck at this issue. 

Can you please guide me ?

**Comment by vatsa287** [comment]
@hardik-pratap-singh Regarding this, It is not possible to send a value/option which is not defined in the `enum` of valid asset types.
Moreover there are checks present in SDK through with the data is in bound to the chain. And on the chain too there is validity check present. 
Since RUST is a compiled time language you cannot pass AssetTypeOf::Invalid in tests too which will throw it is not a part of enum declared.

**Pull request closed without merging**
