### PR TITLE
[CI] Build CORD Docker Image from Github Action for x86-64 Architecture

### PR DESCRIPTION
**Pull request by roynrishingha**
I tested this workflow on my fork and building perfectly.

Test the image:
```
docker pull dhiwayroy/cord:ci-docker-roy
```

Note: It is not compatible with ARM.

### CODE REVIEW

**Comment by roynrishingha** [comment]
@amarts `FROM docker.io/paritytech/ci-unified:latest as builder` was removed due to build error.

**Comment by amarts** [comment]
> @amarts `FROM docker.io/paritytech/ci-unified:latest as builder` was removed due to build error.

Can you keep an issue open to get back this for future usage. We had an issue open from them to use this image instead.

**Review by amarts — APPROVED** [review]

**Comment by amarts** [comment]
Lets get back to working state first, and merge other changes (after confirming). 

Good job!

**Comment by amarts** [comment]
I guess, this should be submitted to `release-0.8.x` branch too.

**Pull request merged**
