### PR TITLE
Add `Makefile` to quickly run commands on CORD.

### PR DESCRIPTION
**Pull request by roynrishingha**
- Remembering all the long commands with all required flags are prone to error.
- Any new developer wants to contribute to `CORD` can progress more ergonomically.

### CODE REVIEW

**Review by amarts — COMMENTED** [review]
/LGTM

Good effort. This will streamline a lot of documentation :-)

**Comment by roynrishingha** [comment]
@amarts A documentation is coming with it in the next commit. This documentation will explain/guide newcomers how to run these `make` commands.

**Comment by amarts** [comment]
Feel free to mark it as 'Ready for review' (ie, not Draft), and I will merge this.

**Comment by roynrishingha** [comment]
@amarts It's ready to merge.

**Review by amarts — DISMISSED** [review]
This is good. One feeling I am getting is, for a README file, this looks very elaborate, by covering everything in one place. Can we keep generic Index of documentation, and something basic (build and run) in front README, and everything else as different files in `docs/` or something similar? (This break up can be a follow-up action with lesser priority, anyone with interest in project can pick that up).

**Comment by roynrishingha** [comment]
@amarts Refactored the `README` and only kept necessary steps. Moved the installation guides into a separate file.

**Review by amarts — APPROVED** [review]

**Comment by NiranjanAP** [comment]
This is awesome, having gone through the setup recently, really appreciate the change here.
I think we can put it to test by asking someone in the team to run through this - 
@ujjwal6792  @sreepriyasree  do you want to try?

**Comment by NiranjanAP** [comment]
Not sure how it is going to work for studio code, lets discuss

**Pull request merged**
