### PR TITLE
Speed up CI build time by using 4-core machine

### PR DESCRIPTION
**Pull request by roynrishingha**
Current Github Action takes on average takes 1 hour. Trying to reduce the CI time by providing a better machine.
I'm hope it'll reduce build time and save us Action minutes.

### CODE REVIEW

**Comment by amarts** [comment]
Here, its waiting for the worker for last 20mins. Can we try with 8 core or even 4 core? That may be good enough IMO.

**Comment by smohan-dw** [comment]
How about using instances from AWS/GCP for this?

**Comment by amarts** [comment]
We are not at a speed where we have more than 1 PR per hour, (70mins is current build time), so I feel optimizing here is not a thing we should be focusing on. This being an opensource project, no pressure on number of minutes too.

**Comment by roynrishingha** [comment]
@amarts why 8 or 4 cores ? Why not 16 cores ?

**Pull request closed without merging**
