### PR TITLE
schema-accounts: Add pallet for accounts based schema management

### PR DESCRIPTION
**Pull request by vatsa287**
This PR,
- adds a new pallet called `schema-accounts` for account based schema accounts.
- removes dependency of `chain-space`. And does not require a `authId` for creation.
- identifier updates.
- update runtime to `0.9.3-1` or `9310`.

### CODE REVIEW

**Review by amarts — COMMENTED** [review]
LGTM.

Few questions, 
* is 9400 better, or 9310 better as newer version?
* is 'schema-accounts' a good name? or something else?
* should schema identifier be different for account based and did based? or should it be using same formula regardless of creator, in which case, we shouldn't use creator identity in schema identifier creation.

**Comment by vatsa287** [comment]
> #is 9400 better, or 9310 better as newer version?

I believe `9310` can be made, and next upcoming PR can have it updated to `9400` when it integrates account based schema with `registries` pallet. I am not sure if both `9300` and `9310` stands for `0.9.3` or it differs.

> is 'schema-accounts' a good name? or something else?

I thought it tells what it is based on, I had something like `schema-registries` on mind as well since it created to work with it. If you find that good or you have something else in mind, please suggest.

> should schema identifier be different for account based and did based? or should it be using same formula regardless of creator, in which case, we shouldn't use creator identity in schema identifier creation.

In `schema` pallet it was based on `creator`, `space_id` & `schema input`. Here it is just `creator` & `schema input`. Please tell me if you want to remove `creator` as part of `identifier`. I believe it is not required, as `schema` here can be public as well. 

^ @amarts

**Comment by amarts** [comment]
> > #is 9400 better, or 9310 better as newer version?
> 
> I believe `9310` can be made, and next upcoming PR can have it updated to `9400` when it integrates account based schema with `registries` pallet. I am not sure if both `9300` and `9310` stands for `0.9.3` or it differs.
> 

9310 is better in that case. 

> > is 'schema-accounts' a good name? or something else?
> 
> I thought it tells what it is based on, I had something like `schema-registries` on mind as well since it created to work with it. If you find that good or you have something else in mind, please suggest.
>

OK for now. Lets take this up again.
 
> > should schema identifier be different for account based and did based? or should it be using same formula regardless of creator, in which case, we shouldn't use creator identity in schema identifier creation.
> 
> In `schema` pallet it was based on `creator`, `space_id` & `schema input`. Here it is just `creator` & `schema input`. Please tell me if you want to remove `creator` as part of `identifier`. I believe it is not required, as `schema` here can be public as well.
> 

The creator needs to be captured for the query, but need not be used for the schema identifier. That way, both pallets use the same logic for identifiers.

**Comment by vatsa287** [comment]
@amarts 
Have updated the identifier logic by keeping only `schema_input` for identifier creation part.

[commit](https://github.com/dhiway/cord/pull/514/commits/dbfc4aa7c6218b0e2564faac4d3dd83e910ac6d1) for ref.

**Review by amarts — APPROVED** [review]

**Pull request merged**
