### PR TITLE
Network-Score : Add Test for RatingIdentierNotFound 

### LINKED ISSUE #300: [C4GT] Network-Score: Add tests for `RatingIdentifierNotFound`
## Description
Subtask under : https://github.com/cord-network/community/issues/7

New testcase can be tested under `cargo test -p pallet-network-score` after adding it in the code.

## Goals

- [ ] Add tests for `RatingIdentifierNotFound` for pallet/network-score

## Expected Outcome
- [ ] Test should assert for `RatingIdentifierNotFound` being returned properly in all the possible calls.
- [ ] If there are more than one function returning this error code, all of them should be validated either as one test case or as multiple test cases.
       
## Acceptance Criteria
NA

## Implementation Details
Look at other test cases, and add a test case for the same.
Ex: In pallets/network-membership check method `test_duplicate_member_request` which validates error code `MembershipAlreadyAcquired`

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
[Low]

## Category
[Test]

## Sub Category
[Beginner friendly]

### PR DESCRIPTION
**Pull request by zeel991**
- Fixes https://github.com/dhiway/cord/issues/300
- This test consists all possible cases where `RatingIdentifierNotFound` Error could have been returned .
- Please review my PR and give feedback if test has any faults .

### CODE REVIEW

**Comment by zeel991** [comment]
Hello @vatsa287 , this test passed on my device

**Comment by zeel991** [comment]
@vatsa287 Can you please give your feedback on the PR

**Review by vatsa287 — APPROVED** [review]
LGTM

**Review by amarts — APPROVED** [review]

**Comment by VedantKhairnar** [comment]
Hello @zeel991   ,
Thanks for your contribution.
As part of Augtoberfest, we want to reward you for your contributions, so pls fill out [this form](https://forms.gle/VBDUPWMYcZEbmVrQ9) by 19th Sept.
Thanks.

**Pull request merged**
